// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl3kZTGQw8xMiJl-wvg5Z5i6ynBEXmMuM',
    appId: '1:500521414393:web:9257eb7c8de493c5183c28',
    messagingSenderId: '500521414393',
    projectId: 'dogesh-the-pet-care-app',
    authDomain: 'dogesh-the-pet-care-app.firebaseapp.com',
    storageBucket: 'dogesh-the-pet-care-app.firebasestorage.app',
    measurementId: 'G-JEVJSQNCVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXlc7I3bXSMY7YCvwDhSI6ZvJG3o2Q-mY',
    appId: '1:500521414393:android:631dbef6efdda416183c28',
    messagingSenderId: '500521414393',
    projectId: 'dogesh-the-pet-care-app',
    storageBucket: 'dogesh-the-pet-care-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeedBFVVlNKiG0TD_ZKisGDucDvlACvGg',
    appId: '1:500521414393:ios:8820d2a8f14ee9dd183c28',
    messagingSenderId: '500521414393',
    projectId: 'dogesh-the-pet-care-app',
    storageBucket: 'dogesh-the-pet-care-app.firebasestorage.app',
    iosBundleId: 'com.dogesh.dogeshApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeedBFVVlNKiG0TD_ZKisGDucDvlACvGg',
    appId: '1:500521414393:ios:8820d2a8f14ee9dd183c28',
    messagingSenderId: '500521414393',
    projectId: 'dogesh-the-pet-care-app',
    storageBucket: 'dogesh-the-pet-care-app.firebasestorage.app',
    iosBundleId: 'com.dogesh.dogeshApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl3kZTGQw8xMiJl-wvg5Z5i6ynBEXmMuM',
    appId: '1:500521414393:web:85299531fc20c994183c28',
    messagingSenderId: '500521414393',
    projectId: 'dogesh-the-pet-care-app',
    authDomain: 'dogesh-the-pet-care-app.firebaseapp.com',
    storageBucket: 'dogesh-the-pet-care-app.firebasestorage.app',
    measurementId: 'G-2BZGDC7XS3',
  );
}
